### ISSUE TITLE
Trouble with Installation

### ISSUE THREAD

**Issue by saharshoza** [open-lambda/open-lambda#17]
I'm trying to install open-lambda. I am running into an error that I do not know how to fix. Here are the steps I followed:
a) export CC=c99 to enable initialization in for loop
b) Go to lambda/nsmodule/fdclient.go and remove commented section of code (This was creating issues with make for some reason)
c) Go to worker/pool-manager/sendFds.go and remove commented section of code
d) make in the lambda/ subdirectory 

Now, I ran make in the root directory of the project. I see the following error. 
github.com/open-lambda/open-lambda/worker/pool-manager
could not determine kind of name for C.sendFds

I'm new to Golang and I'm trying to figure out how to fix this. Any help will be appreciated.

**Comment by tylerharter** [comment]
Looks like the latest commit is broken in my environment as well.  We'll look into this.  In the meantime, perhaps you can try an older commit?

git checkout adc0554b3e8df3a9268bcb2d07be5eb3f6267a82

**Comment by edoakes** [comment]
The "C.sendFds" issue you're seeing now is caused by the removal of the
commented code from the Go files. Those long header comments are actually C
code which is wrapped into the Go package (see https://golang.org/cmd/cgo/),
and then accessed using something similar to "C.functionName()."

Could you show us what the compilation error was prior to removing those
header comments? Also, what version of Go are you running (type "go
version") and on what system?

On Mon, Mar 6, 2017 at 9:32 AM Tyler Harter <notifications@github.com>
wrote:

Looks like the latest commit is broken in my environment as well. We'll
look into this. In the meantime, perhaps you can try an older commit?

git checkout adc0554
<https://github.com/open-lambda/open-lambda/commit/adc0554b3e8df3a9268bcb2d07be5eb3f6267a82>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/open-lambda/open-lambda/issues/17#issuecomment-284430435>,
or mute the thread

**Comment by saharshoza** [comment]
My go version is 1.6.2
I removed my existing project with the edits and pulled from source. Upon make, I got the following error:
```
cd nsmodule && export GOPATH= && go build fdclient.go
# command-line-arguments
./fdclient.go: In function 'sendfd':
./fdclient.go:33:21: error: 'caddr_t' undeclared (first use in this function)
  msg.msg_control = (caddr_t)cms;
                     ^
./fdclient.go:33:21: note: each undeclared identifier is reported only once for each function it appears in
./fdclient.go:33:29: error: expected ';' before 'cms'
  msg.msg_control = (caddr_t)cms;
                             ^
Makefile:6: recipe for target 'ns.so' failed
make[1]: *** [ns.so] Error 2

```
I looked it up and found this [link](https://www.network-builders.com/threads/compile-the-sock-program-in-the-book-tcp-ip-illustrated-vol-1.58013/) that said there should be a #define __USE_BSD 1 for caddr_t to be defined in sys/types.h. 
So I added that to fdclient.h and fdclient.c but I'm still getting the same error.

**Comment by saharshoza** [comment]
I also tried using the checkout id you suggested. I get this error on make
/usr/bin/ld: cannot open output file lambda/nsmodule: Is a directory

**Comment by tylerharter** [comment]
Weird.  Maybe your environment isn't clean?  There shouldn't be a directory called that in the commit you're on: https://github.com/open-lambda/open-lambda/tree/adc0554b3e8df3a9268bcb2d07be5eb3f6267a82/lambda.  Did you try from a clean clone?

Also, what distro are you on?  We will eventually be running tests on a variety of platforms, but we're doing all our dev on Ubuntu 16.04 now, so that's your best bet.
