### ISSUE TITLE
running arbitrary executables

### ISSUE THREAD

**Issue by sdingcn** [open-lambda/open-lambda#56]
Does open-lambda support the execution an arbitrary executable by launching that executable in lambda_func.py? If it supports that, how should I configure it?

**Comment by kaimast** [comment]
Yes. It still needs some documentation but support for it is there.

Essentially, instead of putting a python script in the registry you put a binary (with *.bin ending). That binary needs to be compiled against the docker image OpenLambda is using.
You can look at what `make native-functions` does to understand it better.
